name 'dwerder-graphite'
version '5.3.2'
source 'git clone https://github.com/echocat/puppet-graphite.git'
author 'Daniel Werdermann'
license 'Mozilla Public License Version 2.0'
summary 'Graphite Monitoring Module'
description 'This module installs and makes basic configs for graphite, with carbon and whisper'
project_page 'https://github.com/echocat/puppet-graphite'

dependency   'puppetlabs/stdlib', '>= 3.2.0'
