name 'dwerder-graphite'
version '5.1.1'
source 'git clone https://github.com/echocat/puppet-graphite.git'
author 'Daniel Werdermann'
license 'Mozilla Public License Version 2.0'
summary 'Graphite Monitoring Module'
description 'This module installs and makes basic configs for graphite, with carbon and whisper'
project_page 'https://github.com/echocat/puppet-graphite'
dependency   'puppetlabs/stdlib', '>= 2.2.1'
